name: OCaml

on:
  pull_request:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    # Avoid running twice the action if it's triggered by a push on a PR from a branch on the repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Install OCaml 5.1
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1

      - name: Install dependencies
        run: opam install . --deps-only

      - name: Build
        run: opam exec -- dune build

      - name: Test
        run: opam exec -- dune runtest

  format:
    name: Format
    runs-on: ubuntu-latest

    # Avoid running twice the action if it's triggered by a push on a PR from a branch on the repo.
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Install OCaml 5.1
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.1

      - name: Install dependencies
        run: opam install . --deps-only

      - name: Build
        run: opam exec -- dune build

      - name: Install dune-format
        run: opam install ocamlformat

      - name: Format
        run: opam exec -- dune build @fmt --auto-promote
